# Generated by Django 5.2.1 on 2025-05-18 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Carro', 'verbose_name_plural': 'Carros'},
        ),
        migrations.AlterModelOptions(
            name='carcategory',
            options={'verbose_name': 'Categoria de Carro', 'verbose_name_plural': 'Categorias de Carro'},
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={'verbose_name': 'Modelo de Carro', 'verbose_name_plural': 'Modelos de Carro'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'verbose_name': 'Categoria de Serviço', 'verbose_name_plural': 'Categorias de Serviço'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workshop.brand', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshop.carcategory', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='car',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='workshop.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('flex', 'Flex (Álcool & Gasolina)'), ('alcohol', 'Álcool'), ('gasoline', 'Gasolina'), ('diesel', 'Diesel'), ('hybrid', 'Híbrido')], max_length=20, null=True, verbose_name='Combustível'),
        ),
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(max_length=10, unique=True, verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workshop.carmodel', verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='carcategory',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='workshop.brand', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='service',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='workshop.car', verbose_name='Carro'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshop.servicecategory', verbose_name='Categoria de Serviço'),
        ),
        migrations.AlterField(
            model_name='service',
            name='delivery_time',
            field=models.TimeField(verbose_name='Hora de Entrega'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='service',
            name='labor_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custo de Mão de Obra'),
        ),
        migrations.AlterField(
            model_name='service',
            name='parts_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custo de Peças'),
        ),
        migrations.AlterField(
            model_name='service',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/', verbose_name='Imagem de Recibo'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_date',
            field=models.DateField(verbose_name='Data do Serviço'),
        ),
        migrations.AlterField(
            model_name='service',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Custo Total'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Categoria de Serviço'),
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Geração')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='workshop.carmodel', verbose_name='Modelo de Carro')),
            ],
            options={
                'verbose_name': 'Geração',
                'verbose_name_plural': 'Gerações',
                'unique_together': {('car_model', 'number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='car',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='car',
            name='generation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshop.generation', verbose_name='Geração'),
        ),
        migrations.AlterUniqueTogether(
            name='car',
            unique_together={('brand', 'model', 'generation', 'year', 'client')},
        ),
    ]
