# Generated by Django 5.2.1 on 2025-05-18 02:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_alter_brand_options_alter_car_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name'], 'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['client', 'brand__name', 'model__name', 'generation__number', 'year'], 'verbose_name': 'Carro', 'verbose_name_plural': 'Carros'},
        ),
        migrations.AlterModelOptions(
            name='carcategory',
            options={'ordering': ['name'], 'verbose_name': 'Categoria de Carro', 'verbose_name_plural': 'Categorias de Carro'},
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ['brand__name', 'name'], 'verbose_name': 'Modelo de Carro', 'verbose_name_plural': 'Modelos de Carro'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='generation',
            options={'ordering': ['car_model__brand__name', 'car_model__name', 'number'], 'verbose_name': 'Geração', 'verbose_name_plural': 'Gerações'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-service_date'], 'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['name'], 'verbose_name': 'Categoria de Serviço', 'verbose_name_plural': 'Categorias de Serviço'},
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1886)], verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='generation',
            name='number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Geração'),
        ),
    ]
