# Generated by Django 5.2.1 on 2025-05-18 04:11

import django.core.validators
import django.db.models.deletion
import workshop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0006_alter_client_options_remove_service_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['client', 'license_plate'], 'verbose_name': 'Carro', 'verbose_name_plural': 'Carros'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterUniqueTogether(
            name='car',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='service',
            name='receipt_image',
        ),
        migrations.AddField(
            model_name='service',
            name='confirm_ready',
            field=models.BooleanField(default=False, verbose_name='Confirmado Pronto'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Pago'),
        ),
        migrations.AddField(
            model_name='service',
            name='payment_confirmed_by_admin',
            field=models.BooleanField(default=False, verbose_name='Pagamento Confirmado'),
        ),
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('received', 'Recebido'), ('in_maintenance', 'Em manutenção'), ('ready', 'Pronto'), ('delivered', 'Entregue')], default='received', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='service',
            name='whatsapp_notified',
            field=models.BooleanField(default=False, verbose_name='Cliente Notificado'),
        ),
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Placa inválida. Use o padrão brasileiro (ex: ABC1D23).', regex='^[A-Z]{3}[0-9][A-Z0-9][0-9]{2}$')], verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Número de telefone inválido.', regex='^\\(?\\d{2}\\)?\\s?\\d{4,5}-?\\d{4}$')], verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='service',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Custo Total'),
        ),
        migrations.CreateModel(
            name='CarAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=workshop.models.generate_token, max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_token', to='workshop.car')),
            ],
            options={
                'verbose_name': 'Token de Acesso',
                'verbose_name_plural': 'Tokens de Acesso',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('method', models.CharField(choices=[('cash', 'Dinheiro'), ('debit', 'Débito'), ('credit', 'Crédito'), ('pix', 'Pix')], max_length=10, verbose_name='Forma de Pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='workshop.service')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
            },
        ),
    ]
