# Generated by Django 5.2.1 on 2025-05-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0007_alter_car_options_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
