# Generated by Django 5.2.1 on 2025-05-18 04:41

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0008_service_receipt_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalService',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('labor_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custo de Mão de Obra')),
                ('parts_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custo de Peças')),
                ('total_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Custo Total')),
                ('service_date', models.DateField(verbose_name='Data do Serviço')),
                ('delivery_time', models.TimeField(verbose_name='Hora de Entrega')),
                ('status', models.CharField(choices=[('received', 'Recebido'), ('in_maintenance', 'Em manutenção'), ('ready', 'Pronto'), ('delivered', 'Entregue')], default='received', max_length=20, verbose_name='Status')),
                ('confirm_ready', models.BooleanField(default=False, verbose_name='Confirmado Pronto')),
                ('whatsapp_notified', models.BooleanField(default=False, verbose_name='Cliente Notificado')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Pago')),
                ('payment_confirmed_by_admin', models.BooleanField(default=False, verbose_name='Pagamento Confirmado')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Atualizado em')),
                ('receipt_image', models.TextField(blank=True, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('car', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workshop.car', verbose_name='Carro')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Serviço',
                'verbose_name_plural': 'historical Serviços',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
