# Generated by Django 5.2.1 on 2025-05-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0010_alter_car_license_plate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalservice',
            name='is_budgeted',
            field=models.BooleanField(default=False, verbose_name='Orçamento Confirmado'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_budgeted',
            field=models.BooleanField(default=False, verbose_name='Orçamento Confirmado'),
        ),
        migrations.AlterField(
            model_name='historicalservice',
            name='labor_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo de Mão de Obra'),
        ),
        migrations.AlterField(
            model_name='historicalservice',
            name='parts_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo de Peças'),
        ),
        migrations.AlterField(
            model_name='historicalservice',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Custo Total'),
        ),
        migrations.AlterField(
            model_name='service',
            name='labor_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo de Mão de Obra'),
        ),
        migrations.AlterField(
            model_name='service',
            name='parts_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo de Peças'),
        ),
        migrations.AlterField(
            model_name='service',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Custo Total'),
        ),
    ]
