# Generated by Django 5.2.1 on 2025-05-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0011_historicalservice_is_budgeted_service_is_budgeted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalservice',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
