# Generated by Django 5.2.1 on 2025-05-19 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0012_alter_historicalservice_total_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalservice',
            name='confirm_ready',
        ),
        migrations.RemoveField(
            model_name='historicalservice',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='historicalservice',
            name='payment_confirmed_by_admin',
        ),
        migrations.RemoveField(
            model_name='service',
            name='confirm_ready',
        ),
        migrations.RemoveField(
            model_name='service',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='service',
            name='payment_confirmed_by_admin',
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='deadline_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Prazo'),
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='email_notified',
            field=models.BooleanField(default=False, verbose_name='E-mail Notificado'),
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='service_type',
            field=models.CharField(choices=[('diagnosis', 'Diagnóstico'), ('maintenance', 'Manutenção'), ('repair', 'Reparo'), ('other', 'Outro')], default='diagnosis', max_length=20, verbose_name='Tipo de Serviço'),
        ),
        migrations.AddField(
            model_name='service',
            name='deadline_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Prazo'),
        ),
        migrations.AddField(
            model_name='service',
            name='email_notified',
            field=models.BooleanField(default=False, verbose_name='E-mail Notificado'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('diagnosis', 'Diagnóstico'), ('maintenance', 'Manutenção'), ('repair', 'Reparo'), ('other', 'Outro')], default='diagnosis', max_length=20, verbose_name='Tipo de Serviço'),
        ),
        migrations.AlterField(
            model_name='historicalservice',
            name='delivery_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Entrega'),
        ),
        migrations.AlterField(
            model_name='historicalservice',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='historicalservice',
            name='receipt_image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Recibo'),
        ),
        migrations.AlterField(
            model_name='historicalservice',
            name='status',
            field=models.CharField(choices=[('received', 'Recebido'), ('budgeted', 'Orçado'), ('in_progress', 'Em Andamento'), ('ready', 'Pronto'), ('delivered', 'Entregue')], default='received', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalservice',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Custo Total'),
        ),
        migrations.AlterField(
            model_name='service',
            name='delivery_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Entrega'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='service',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/', verbose_name='Recibo'),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('received', 'Recebido'), ('budgeted', 'Orçado'), ('in_progress', 'Em Andamento'), ('ready', 'Pronto'), ('delivered', 'Entregue')], default='received', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='service',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Custo Total'),
        ),
    ]
