# Generated by Django 5.2.1 on 2025-05-19 02:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0013_remove_historicalservice_confirm_ready_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-entry_date'], 'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
        migrations.RemoveField(
            model_name='historicalservice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='historicalservice',
            name='delivery_time',
        ),
        migrations.RemoveField(
            model_name='historicalservice',
            name='service_date',
        ),
        migrations.RemoveField(
            model_name='historicalservice',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='service',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='service',
            name='delivery_time',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_date',
        ),
        migrations.RemoveField(
            model_name='service',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora de Conclusão'),
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='current_km',
            field=models.PositiveIntegerField(blank=True, help_text='Quilometragem atual do veículo', null=True, verbose_name='Quilometragem Atual'),
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora de Entrega'),
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='entry_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Data/Hora de Entrada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora de Início'),
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='technician',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Técnico Responsável'),
        ),
        migrations.AddField(
            model_name='service',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora de Conclusão'),
        ),
        migrations.AddField(
            model_name='service',
            name='current_km',
            field=models.PositiveIntegerField(blank=True, help_text='Quilometragem atual do veículo', null=True, verbose_name='Quilometragem Atual'),
        ),
        migrations.AddField(
            model_name='service',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora de Entrega'),
        ),
        migrations.AddField(
            model_name='service',
            name='entry_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data/Hora de Entrada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora de Início'),
        ),
        migrations.AddField(
            model_name='service',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Técnico Responsável'),
        ),
    ]
