# Generated by Django 5.2.1 on 2025-05-19 03:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0016_alter_car_options_alter_caraccesstoken_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Placa inválida', regex='^[A-Z]{3}-?[0-9]{4}$|^[A-Z]{3}[0-9][A-Z][0-9]{2}$')], verbose_name='Placa'),
        ),
    ]
