# Generated by Django 5.2.1 on 2025-05-19 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0017_alter_car_license_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalservice',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Custo total'),
        ),
        migrations.AlterField(
            model_name='service',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Custo total'),
        ),
    ]
